apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: dwnkim
spec:
  owner:
    kind: User
    name: dwnkim@example.com  # 변경된 소유자
  resourceQuotaSpec:
    hard:
#       cpu: "100"
#       memory: 100Gi
      persistentvolumeclaims: "20"
      requests.nvidia.com/gpu: "10"
