apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: shared-private-rwm
  namespace: dwnkim # <--- 적용할 유저 네임스페이스로 변경하세요! (여러 곳이면 여러 번 배포)
spec:
  desc: "개인 데이터셋 연결 (testfield - ReadWriteMany)"
  selector:
    matchLabels:
      shared-private-rwm: "true"
  volumeMounts:
    - name: shared-private-rwm
      mountPath: /home/jovyan/private-nas
  volumes:
    # 실제 NFS 서버 정보 입력 (PV/PVC를 거치지 않고 직접 연결하여 충돌 방지)
    - name: shared-private-rwm
      nfs:
        server: 192.168.0.200       # NFS 서버 IP
        path: /volume1/testfield/GPU_storage/Private_storage/dwnkim # NFS 실제 경로
        readOnly: false
