apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-kubeflow-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kubeflow-storage
  resources:
    requests:
      storage: 1Gi
