apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubeflow-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-kubeflow-provisioner
parameters:
  archiveOnDelete: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
  - nolock
